### ISSUE TITLE
Call to undefined function wfMsg()

### ISSUE THREAD

**Issue by LloydRutledge** [LloydRutledge/FresnelForms#2]
[[Special:OWLwikiForms]] 

https://www.mediawiki.org/wiki/Topic:Tccakhq97grwav0i

I[6f834b1c35c289d4bcc07756] /FF/index.php/Special:OWLwikiForms Error from line 31 of C:\xampp\htdocs\FF\extensions\OWLwikiForms\SpecialOWLwikiForms.php: Call to undefined function wfMsg()

Backtrace:

#0 C:\xampp\htdocs\FF\includes\specialpage\SpecialPage.php(522): SpecialOWLwikiForms->execute(NULL)
#1 C:\xampp\htdocs\FF\includes\specialpage\SpecialPageFactory.php(578): SpecialPage->run(NULL)
#2 C:\xampp\htdocs\FF\includes\MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#3 C:\xampp\htdocs\FF\includes\MediaWiki.php(851): MediaWiki->performRequest()
#4 C:\xampp\htdocs\FF\includes\MediaWiki.php(523): MediaWiki->main()
#5 C:\xampp\htdocs\FF\index.php(43): MediaWiki->run()
#6 {main}

**Comment by LloydRutledge** [comment]
fix with wfMessage
